MARKET/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('landing.urls')),
                  path('order/', include('order.urls')),
                  path('customer/', include('customer.urls')),
                  path('product/', include('product.urls')),

              ]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

landing/urls.py
from django.urls import path
from .views import *


app_name = 'landing'

urlpatterns = [
    path('contact_us/', ContactUsView.as_view(), name='contact_us'),
    path('contact_us_ajax/', contact_us, name='contact_us_ajax'),
    path('', HomeView.as_view(), name='index'),
    path('home/', HomeView.as_view(), name='home'),
    path('access_denied/', AccessDenied.as_view(), name='access_denied'),

]

order/urls.py
from django.urls import path
from .views import *


app_name = 'order'

urlpatterns = [
    path('order_items/', OrderItemIndexView.as_view(), name='order_items_index'),
    # path('order_item/<int:pk>', OrderItemDetailView.as_view(), name='order_item_detail'),
    # path('add_order_item/', OrderItemFormView.as_view(), name='add_order_item_form'),
    path('cart/', CartView.as_view(), name='customer_cart'),
    path('cart/confirmed/', CartConfirmedMessageView.as_view(), name='cart_confirm'),
    path('cart/canceled/', CartCanceledMessageView.as_view(), name='cart_cancel'),
    path('api/orderitems-list/', OrderItemListAPIView.as_view(), name='orderitems_api_for_admin'),
    path('api/cart-list/', CartAPIView.as_view(), name='cart_list_api_for_admin'),
    path('api/cart/', CartCustomerAPIView.as_view(), name='customer_cart_api'),
    path('api/cart/orderitems/', CartOrderItemsAPIView.as_view(), name='customer_cart_orderitems_api'),
    path('api/cart/orderitems/<int:pk>', OrderItemDetailAPIView.as_view(), name='customer_cart_orderitems_details_api'),
    path('api/cart/add_orderitem/', CartOrderItemCreateAPIView.as_view(), name='customer_cart_orderitems_create_api'),
    path('sp_cart/', single_page_cart_view, name='single_page_cart'),

]

product/urls.py
from django.urls import path
from .views import *


app_name = 'product'

urlpatterns = [
    path('', ProductIndexView.as_view(), name='product_index'),
    # path('card/<int:pk>', ProductCardView.as_view(), name='product_card'),
    path('<int:pk>', ProductDetailsView.as_view(), name='product_details'),
    path('category/<int:id>', CategoryView.as_view(), name='category_card'),
    # path('products_api/', product_list_view_api, name='products_api'),
    path('api/products/', ProductAPIView.as_view(), name='all_products_api_for_admin'),
    path('api/products/<int:pk>', ProductDetailsAPIView.as_view(), name='product_details_api_for_admin'),
    path('api/products-list/', ProductsIndexAPIView.as_view(), name='products_index_api'),
    path('api/products-list/<int:pk>', ProductDetailsIndexAPIView.as_view(), name='product_details_api'),
    path('api/categories/', CategoryListAPIView.as_view(), name='categories_api_for_admin'),
    path('api/categories/<int:pk>', CategoryDetailAPIView.as_view(), name='categories_details_api_for_admin'),
    path('api/categories-list/', CategoryIndexAPIView.as_view(), name='categories_index_api'),
    path('api/categories-list/<int:pk>', CategoryDetailsIndexAPIView.as_view(), name='category_details_api'),
    path('api/discounts/', DiscountAPIView.as_view(), name='discounts_api_for_admin'),
    path('api/discounts/<int:pk', DiscountDetailAPIView.as_view(), name='discount_detail_api_for_admin'),

]

templates/base.html
{% load i18n %}
{% load static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" dir="{{ LANGUAGE_BIDI|yesno:'rtl,ltr,auto' }}">
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'shared/css/bootstrap.min.css' %}">
    {% block stylesheet %}
        <link rel="stylesheet" href="{% static 'shared/css/base.css' %}">
    {% endblock %}
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    {#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>#}
    {#    <script type="text/JavaScript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>#}
    {#    <script src="https://code.jquery.com/jquery-1.10.1.min.js"></script>#}
    {% block css %}
        <style>
            html, body {
                height: 100%;
            }

            body {
                margin: 0;
                padding: 0;
                font-size: 14px;
                font-family: "Roboto", "Lucida Grande", "DejaVu Sans", "Bitstream Vera Sans", Verdana, Arial, sans-serif;
                color: black;
                background: #f3f2f2;
            }

            #header {
                position: sticky;
                top: 0;
                z-index: 1;
                width: 100%;
                height: auto;
                display: flex;
                justify-content: space-between;
                padding: 5px 5px;

                background-color: rgb(74, 8, 218);
                color: white;
            }

            .topnav a, .topnav input[type=text], .topnav .search-container button {
                float: none;
                display: block;
                text-align: left;
                width: 100%;
                margin: 0;
                padding: 14px;
            }

            {##branding a {}#}

            #header input[type=text] {
                border: 1px solid #ccc;
            }

            #footer {
                position: relative;
                bottom: 0;

                width: 100%;
                display: flex;
                color: #c9f2fe;
                /*justify-content: space-between;*/
                /*padding: 15px 20px;*/
                /*align-items: center;*/
                background-color: rgb(74, 8, 218);
                min-height: 1rem;
            }


    {% endblock %}
    {% block extrastyle %}{% endblock %}</style>
    {#{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "" %}{% endblock %}">{% endif %}#}
    {% block extrahead %}{% endblock %}
    {#{% block responsive %}#}
    {#    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">#}
    {#    <link rel="stylesheet" type="text/css" href="{% static "" %}">#}
    {#    {% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% static "" %}">{% endif %}#}
    {#{% endblock %}#}
    <meta charset="UTF-8">

</head>
{% load i18n %}
<body id="body">
<div id="header" class="container-fluid p-0 m-0 pt-2" style="background-color: #1b1e21">
    <div id="topnav" class="container-fluid header pl-3 pr-3 pt-1 m-auto">
        <div id="siteheader" class="row" style="height: 45px">
            <div id="products" class="col-4 float-left">
                <a href="{% url 'product:product_index' %}">
                    <button class="btn btn-outline-light">
                        <strong><i class="fa fa-list"></i></strong> {% translate 'All Products' %}</button>
                </a>
                <a href="{% url 'landing:home' %}">
                    <button class="btn btn-outline-light"><strong><i class="fa fa-home"></i></strong>
                        {% translate 'Home' %}</button>
                </a>
                <a href="{% url 'landing:contact_us' %}">
                    <button class="btn btn-outline-light"><strong><i class="fa fa-envelope"></i></strong>
                        {% translate 'Contact Us' %}</button>
                </a>

                {#                <a href="{% url 'product:product_index' %}"><button class="btn btn-outline-light">#}
                {#                    {% translate 'Categories' %}</button></a>#}

            </div>
            <div id="branding" class="col-4 text-center">
                {% block branding %}
                    <a href="/home/" style="text-decoration: none"><h3 class="text-white">{% translate 'MARKET' %}</h3></a>
                {% endblock %}
            </div>
            {#            <div class="search-container">#}
            {#                <form action="">#}
            {#                    <input type="text" placeholder="{% translate 'Search ...' %}" name="search"#}
            {#                           style="position: fixed; left: 160px; padding: 6.5px; border-radius: 5px" ; size="70px">#}
            {#                    <button type="submit" class="btn btn-light" style="position: fixed; left: 750px; padding: 5px"><i#}
            {#                            class="fa fa-search"></i></button>#}
            {#                </form>#}
            {##}
            {#            </div>#}
            <div id="user-tools" class="col-3 float-right text-right">
                {% if request.user.is_authenticated %}
                    <a href="/customer/dashboard/">
                        <button class="btn btn-info">{% translate 'Account' %}
                            <strong><i class="fa fa-user"></i></strong></button>
                    </a>
                    <a href="/customer/logout/">
                        <button class="btn btn-danger">{% translate 'Logout' %}
                            <strong><i class="fa fa-sign-out"></i></strong></button>
                    </a>

                {% else %}
                    <a href="/customer/login/">
                        <button class="btn btn-success">{% translate 'Login' %}
                            <strong><i class="fa fa-sign-in"></i></strong></button>
                    </a>
                {% endif %}


            </div>
            <div id="cart" class="col-1 float-right">
                <a href="/order/cart/">
                    <button class="btn btn-outline-light">{% translate 'Cart' %} <strong><i
                            class="fa fa-shopping-cart"></i></strong></button>
                </a>
            </div>

        </div>

    </div>
</div>


<div id="content" style=" min-height: 84.5vh">
    {% block content %}
    {% endblock %}
</div>
<div id="footer" class="container-fluid text-center" style="background-color: #1b1e21">

    {% block footer %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <p style=" padding-left: 0.5rem; padding-top: 0.85rem">Contact Us : <i
                            class="fa fa-phone-square fa-lg"> </i> 09123456789 <i
                            class="fa fa-envelope-square fa-lg"> </i> market@best_market.com <i
                            class="fa fa-map-marker fa-lg"> </i> Tehran, Milad Tower, MARKET </p>
                </div>

            </div>
        </div>
    {% endblock %}
</div>
</body>
</html>